weights: .
cfg: models/PeT.yaml
data: data/detection.yaml
hyp: data/hyps/hyp.ip102.yaml
epochs: 400
batch_size: 32
imgsz: 640
resume: false
nosave: false
noval: false
noautoanchor: false
noplots: false
evolve: null
cache: null
image_weights: false
device: '0'
optimizer: SGD
sync_bn: false
workers: 8
project: runs/train
name: exp
exist_ok: false
quad: false
cos_lr: true
label_smoothing: 0.0
patience: 100
freeze: false
save_period: -1
seed: 0
local_rank: -1
bucket: ''
entity: null
save_dir: runs/train/exp
